fix: replace `sha512sum` with `shasum -a 512`
For better cross-platform compatibility of git hooks.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,8 +1,9 @@
 #!/bin/bash
 
 VERSION=${1:-512}
-SHA=sha"$VERSION"
-COMMAND="$SHA"sum
+EXEC=shasum
+CMD="$EXEC -a $VERSION"
+SHA="sha$VERSION"
 
 INPUT=docs/nominatim.openapi.json
 OUTPUT="$INPUT".checksum
@@ -13,14 +14,15 @@ then
     exit 1
 fi
 
-if ! command -v $COMMAND &> /dev/null
+if ! command -v $EXEC &> /dev/null
 then
-    echo "$COMMAND could not be found, please install it"
+    echo "$EXEC could not be found, please install it"
     exit 1
 fi
 
-CHECKSUM=`$COMMAND $INPUT | awk '{print $1}'`
+CHECKSUM=`$CMD $INPUT | awk '{print $1}'`
 
-echo "$SHA-$CHECKSUM"
+echo "Checksum ($OUTPUT): $SHA-$CHECKSUM"
 echo -n "$SHA-$CHECKSUM" > $OUTPUT
 git add $OUTPUT
+exit 0
diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,8 +1,9 @@
 #!/bin/bash
 
 VERSION=${1:-512}
-SHA=sha"$VERSION"
-COMMAND="$SHA"sum
+EXEC=shasum
+CMD="$EXEC -a $VERSION"
+SHA="sha$VERSION"
 
 INPUT=docs/nominatim.openapi.json
 OUTPUT="$INPUT".checksum
@@ -13,13 +14,13 @@ then
     exit 1
 fi
 
-if ! command -v $COMMAND &> /dev/null
+if ! command -v $EXEC &> /dev/null
 then
-    echo "$COMMAND could not be found, please install it"
+    echo "$EXEC could not be found, please install it"
     exit 1
 fi
 
-CHECKSUM=`$COMMAND $INPUT | awk '{print $1}'`
+CHECKSUM=`$CMD $INPUT | awk '{print $1}'`
 
 if [ ! -f $OUTPUT ]
 then
@@ -27,8 +28,11 @@ then
     exit 1
 fi
 
-if ! grep $CHECKSUM $OUTPUT &>/dev/null
+if ! grep "$SHA-$CHECKSUM" $OUTPUT &>/dev/null
 then
     echo "wrong checksum, please verify"
     exit 1
 fi
+
+echo "Checksum ($OUTPUT): $SHA-$CHECKSUM"
+exit 0
